# Package Overview
package_name: titanic_repo

# Data Files
train_data_file: train.csv
test_data_file: test.csv
y_test_data_file: y_test.csv

# VARIABLES
# Target
target: Survived

pipeline_name: src
pipeline_save_file: titanic_classification_model

features:
  - Pclass
  - Name
  - Sex
  - Age
  - SibSp
  - Parch
  - Ticket
  - Fare
  - Cabin
  - Embarked

# set train/test split
test_size: 0.15

# to set the random seed
random_state: 1991

var_to_extract_letter: Cabin

var_to_extract_title: Name

# New var name after title extraction from Name
title_var_name: Title

# variables to drop
vars_to_drop:
  - Name
  - Ticket

numerical_vars:
  - Pclass
  - Age
  - SibSp
  - Parch
  - Fare

categorical_vars:
  - Sex
  - Cabin
  - Embarked
  - Title

